// @title WalletApp API
// @version 1.0
// @description API for wallet application
// @host localhost:8080
// @BasePath /api

package main

import (
	"log"
	_ "walletapp/docs" // docs is generated by Swag CLI, you have to import it.
	"walletapp/internal/db"
	"walletapp/internal/handlers"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	// Load .env file
	err := godotenv.Load(".env") // Adjust path based on where your .env file is
	if err != nil {
		log.Println("No .env file found")
	}

	db.Connect()
	router := gin.Default()

	// Redirect home page to Swagger UI
	router.GET("/", func(c *gin.Context) {
		c.Redirect(302, "/swagger/index.html")
	})

	// Swagger route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Grouped routes
	api := router.Group("/api")
	{
		// User
		api.GET("/users", handlers.GetUsers)
		api.GET("/users/:id", handlers.GetUserByID)
		api.POST("/users", handlers.CreateUser)

		// Wallet
		api.POST("/wallets/:user_id/deposit", handlers.Deposit)
		api.POST("/wallets/:user_id/withdraw", handlers.Withdraw)
		api.GET("/wallets/:user_id/balance", handlers.GetBalance)

		// Transaction
		api.POST("/wallets/transfer", handlers.Transfer)
		api.GET("/wallets/:user_id/transactions", handlers.GetTransactionHistory)
	}

	router.Run(":8080")
}
